[project]
site_name = "Ansible Best Practices"
site_description = "Best Practices and Style Guide for Ansible Projects"
site_author = "Tim Grützmacher"
site_url = "https://timgrt.github.io/Ansible-Best-Practices/"
copyright = "Copyright &copy; Tim Grützmacher 2026"

repo_url = "https://github.com/TimGrt/Ansible-Best-Practices"
repo_name = "TimGrt/Ansible-Best-Practices"

extra_javascript = [
    "https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js",
    "assets/javascripts/extra/tablesort.js"
]

extra_css = [
    "assets/stylesheets/extra.css",
    "assets/stylesheets/tables.css"
]

nav = [
  {"Ansible Best Practice Guide" = "index.md"},
  {"Mindset" = "mindset/index.md"},
  {"Get started" = "get-started/index.md"},
  {"Ansible" = [
      "ansible/index.md",
      {"Installation" = "ansible/installation.md"},
      {"Project structure" = "ansible/project.md"},
      {"Inventory" = "ansible/inventory.md"},
      {"Playbook" = "ansible/playbook.md"},
      {"Collections" = "ansible/collections.md"},
      {"Roles" = "ansible/roles.md"},
      {"Tasks" = "ansible/tasks.md"},
      {"Variables" = "ansible/variables.md"},
  ]},
  {"Ansible Automation Platform" = [
      "automation-platform/index.md",
      {"Job Templates" = "automation-platform/job-templates.md"},
      {"Credentials" = "automation-platform/credentials.md"},
      {"Workflows" = "automation-platform/workflows.md"},
      {"Operations" = "automation-platform/operations.md"},
  ]},
  {"Ansible Development" = [
      "development/index.md",
      {"Version Control" = "development/git.md"},
      {"Linting" = "development/linting.md"},
      {"Testing" = "development/testing.md"},
      {"Extending" = "development/extending.md"},
      {"Monitoring & Troubleshooting" = "development/monitoring.md"},
  ]},
]
# ----------------------------------------------------------------------------
# Section for configuring theme options
# ----------------------------------------------------------------------------
[project.theme]
variant = "modern"

custom_dir = "docs/assets/overrides"

logo = "assets/images/ansible-logo-black.png"
favicon = "assets/images/ansible-logo-black.png"

language = "en"

# Zensical provides a number of feature toggles that change the behavior
# of the documentation site.
features = [
    # "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.footnote.tooltips",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
    "toc.integrate"
]

# ----------------------------------------------------------------------------
# The "theme" defines colors and more.
# ----------------------------------------------------------------------------
[project.theme.icon.admonition]
example = "lucide/search-code"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
palette.primary = "red"
palette.accent = "blue"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
palette.primary = "blue"
palette.accent = "red"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

# ----------------------------------------------------------------------------
# The "extra" section contains miscellaneous settings.
# ----------------------------------------------------------------------------
[[project.extra.social]]
icon = "octicons/person-add-24"
link = "https://github.com/TimGrt/Ansible-Best-Practices"
name = "Original Repository"

[[project.extra.social]]
icon = "simple/githubactions"
link = "https://github.com/TimGrt/Ansible-Best-Practices/actions"
name = "CI/CD Pipelines"

[[project.extra.social]]
icon = "fontawesome/brands/docker"
link = "https://github.com/TimGrt/Ansible-Best-Practices/pkgs/container/ansible-best-practices"
name = "Docker Container in Github Container Repository"

# ----------------------------------------------------------------------------
# Markdown Extensions
# ----------------------------------------------------------------------------
# https://zensical.org/docs/setup/extensions/python-markdown/#abbreviations
[project.markdown_extensions.abbr]
# https://zensical.org/docs/setup/extensions/python-markdown/#admonition
[project.markdown_extensions.admonition]
# https://zensical.org/docs/setup/extensions/python-markdown/#attribute-lists
[project.markdown_extensions.attr_list]
# https://zensical.org/docs/setup/footer/#configuration
[project.markdown_extensions.footnotes]
# https://zensical.org/docs/setup/extensions/python-markdown/#markdown-in-html
[project.markdown_extensions.md_in_html]
# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#caption
[project.markdown_extensions.pymdownx.blocks.caption]
# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#details
[project.markdown_extensions.pymdownx.details]
# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#emoji
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#highlight
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
linenums_style = "pymdownx-inline"
pygments_lang_class = true
# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#inlinehilite
[project.markdown_extensions.pymdownx.inlinehilite]
# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#snippets
[project.markdown_extensions.pymdownx.snippets]
auto_append = ["includes/abbreviations.md"]
base_path = [".", "docs/ansible/snippets", "docs/automation-platform/snippets"]
# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#superfences
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
# https://zensical.org/docs/authoring/content-tabs/#content-tabs
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
# https://zensical.org/docs/setup/navigation/#instant-previews
[project.markdown_extensions.zensical.extensions.preview]
configurations = [
    { targets.include = [
        "ansible/*",
        "automation-platform/*",
        "development/*",
        "get-started/*",
        "mindset/*"
    ]}
]